# on: [push, pull_request]
on:
  pull_request:
    types: [opened, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    name: Slack Notification
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Success
        run: exit 0
      - name: Action
        uses: ./
        if: always()
        with:
          event: ${{ toJson(github.event) }}
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: pr
